// Automatically generated by astro-icon
// b993985eccae483c4e9714f21afa94fdc5b673ef7f2de954fc672f34b35f86cd

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arcticons:mail"
		| "arcticons:github"
		| "arcticons:linkedin"
		| "arcticons:x-twitter"
		| "arcticons:document-viewer";
}