// Automatically generated by astro-icon
// c165620b1ed2c8f57b85a69542c5a2ac96ec73a5e8d6bdd050007cd4a76e5dc5

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arcticons:mail"
		| "arcticons:github"
		| "arcticons:linkedin"
		| "arcticons:x-twitter"
		| "arcticons:pdf-file"
		| "arcticons:instagram";
}