// Automatically generated by astro-icon
// 456688bab61c38008b637895d0f99d9159c3265e65bc84874c849d63c198952b

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "ph:head-circuit-thin"
		| "ph:envelope-thin"
		| "ph:github-logo-thin"
		| "ph:linkedin-logo-thin"
		| "ph:instagram-logo-thin"
		| "ph:file-pdf-thin"
		| "ph:megaphone"
		| "ph:quotes";
}