version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 0
    allow:
      - dependency-type: direct
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
