version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    allow:
      - dependency-type: direct
    versioning-strategy: increase-if-necessary
    target-branch: "dev"
    open-pull-requests-limit: 10
    schedule:
      interval: daily
    groups:
      dev-deps:
        dependency-type: development
      prod-deps:
        dependency-type: production
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: "dev"
    schedule:
      interval: daily
